### ISSUE TITLE
A simple seismic imaging exercise

### ISSUE THREAD

**Issue by kwinkunks** [softwareunderground/repro-zoo#21]
Russell, B (1998). A simple seismic imaging exercise. The Leading Edge 17, p 885. DOI: [10.1190/1.1438059](http://dx.doi.org/10.1190/1.1438059)

Not really open, but intended to be reproduced... on paper. Not certain, but I think it might work in code. Could be fun.

**Comment by NicolasCami** [comment]
I read the article, it's easy to understand and crystal clear. But I'm not sure what we can do in terms of code. Did you imagine a Python program that reproduce the figures of this paper, allowing the user to tweak some parameters (like S/R location and the dip angle)?

**Comment by fr1ll** [comment]
@NicolasCami I like that idea. I was thinking you could even start by making the equations using [desmos](https://www.desmos.com/calculator).

I have an interactive AVA calculator [here](https://huggingface.co/spaces/fr1ll/wb-avo) using Bruges, these kinds of things are nice to mess with.

**Comment by NicolasCami** [comment]
I started a notebook to reproduce Figure 1 and 2: https://github.com/NicolasCami/repro-zoo/blob/russel-1998/russel-1998/russel-1998.ipynb
It's funny, although not difficult. Do you think it's worth going further?

**Comment by fr1ll** [comment]
@NicolasCami I think your figures look good!

Reading the code already helps me to understand the paper better.

As for what's worth doing, I think the other two figures are useful. You've already done the hard part by setting these ones up. I could probably add the other two if you are a bit tired of this.

I also think it would be really cool to add interactivity. Here's a few possible methods:
- Use [Jupyter Widgets + Quarto](https://quarto.org/docs/interactive/widgets/jupyter.html) and host on Github Pages
- Use Panel, [convert to a web page](https://towardsdatascience.com/how-to-deploy-a-panel-visualization-dashboard-to-github-pages-2f520fd8660), and host on Github Pages
- Use [Streamlit](https://docs.streamlit.io/library/api-reference/charts/st.pyplot) within [Jupyter](https://github.com/ddobrinskiy/streamlit-jupyter) and host on [Huggingface Spaces](https://huggingface.co/spaces/fr1ll/simple-seismic-exercise)
- Convert to [Curvenote document](https://curvenote.com/docs/jupyter/reproducible-figures)

Any of those options would probably involve lots of fiddly things to set up. They would also benefit greatly from the work you already did to make the notebook. Any thoughts on these? I would be glad to help with one of them, but don't have a strong feeling that one direction is the best.

**Comment by NicolasCami** [comment]
@fr1ll Thanks for the positive and relevant feedback. I'll have a look at these methods. I'm new to Jupyter notebook (I'm actually a C++ developer) and I find it very convenient. If I can plug some widgets within the notebook it would be awesome

**Comment by NicolasCami** [comment]
@fr1ll I looked at Jupyter Widgets and managed to get it working locally but as it requires an active backend which Github doesn't provide, we would need another service to bring interactivity into Github (as you mentioned). As I don't like to multiply services and complexity, mainly for eco-design reasons, I'd like to keep the solution simple. I propose to create a second Jupyter notebook using Widgets that users can download and play with if they wish.
I finished the 8 figures of the paper: https://github.com/NicolasCami/repro-zoo/blob/russel-1998/russel-1998/russel-1998.ipynb

**Comment by fr1ll** [comment]
@NicolasCami this looks awesome. I like the idea of creating a second version with sliders etc. -- since you've already done the hard work to make these figures, it makes it pretty easy for me to experiment with different ways.

~~I may try at very least to use Curvenote.~~ Here is how it looks with [Curvenote](https://curvenote.com/@fr1ll/simple-seismic-exercise/russel-1998) just with a naive upload. I do think this is a little dead-end because it's divorced from the Github repo. I agree it's pretty annoying to have multiple versions in multiple locations...

The dream for me would be to have a hosted version that pulls straight from `git`. I will do some looking.

**Comment by NicolasCami** [comment]
@fr1ll Thanks for the feedback. I just pushed a new commit to cleanup the notebook (variable naming, better explanations, adding titles).

As for Curvenote, if it's not synchronized with this repo, I guess it's hard to maintain (even if I don't expect this notebook to change in the future). I let you investigate further.

Do you want me to create a pull request to integrate what has already been done?

**Comment by kwinkunks** [comment]
Closedby https://github.com/softwareunderground/repro-zoo/pull/64
